# ===== Modello e dataset =====
model: TransERecBole
dataset: ml-100k
data_path: /home/ricchiuti/_env/lib/python3.8/site-packages/recbole/dataset_example/ml-100k

# ===== Campi obbligatori =====
USER_ID_FIELD: user_id
ITEM_ID_FIELD: item_id
ENTITY_ID_FIELD: entity_id
HEAD_ENTITY_ID_FIELD: head_id
TAIL_ENTITY_ID_FIELD: tail_id
RELATION_ID_FIELD: relation_id

# ===== Training =====
epochs: 30
train_batch_size: 512
learner: adam
learning_rate: 0.001
train_neg_sample_args:
    distribution: uniform
    sample_num: 3
    alpha: 1.0
    dynamic: False

# ===== Model parameters =====
embedding_size: 128
margin: 1.0
alpha: 0.5
clip_grad_norm:
  max_norm: 1.0
  norm_type: 2
l2_reg: 1e-4

# ===== Evaluation =====
eval_args:
  split:
    RS: [0.8, 0.1, 0.1]
  order: RO
  group_by: user
  mode:
    valid: uni100
    test: full
  negative_sampling:
    distribution: uniform
    eval_sample_num: 100
    filter_by_interaction: True
metrics: [Recall, Precision, NDCG, MRR, Hit]
topk: [5, 10, 20]
valid_metric: Recall@10
valid_metric_bigger: True
eval_batch_size: 1024

# ===== Altri =====
seed: 2024
reproducibility: True
use_gpu: True
device: cuda
tensorboard: True
save_model: True
log_wandb: False
gpu_id: 7
